// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/money_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// запрос на получение
type GetSavingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavingsRequest) Reset() {
	*x = GetSavingsRequest{}
	mi := &file_proto_money_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavingsRequest) ProtoMessage() {}

func (x *GetSavingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_money_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavingsRequest.ProtoReflect.Descriptor instead.
func (*GetSavingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_money_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSavingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ответ
type GetSavingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSavings  float64                `protobuf:"fixed64,1,opt,name=total_savings,json=totalSavings,proto3" json:"total_savings,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavingsResponse) Reset() {
	*x = GetSavingsResponse{}
	mi := &file_proto_money_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavingsResponse) ProtoMessage() {}

func (x *GetSavingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_money_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavingsResponse.ProtoReflect.Descriptor instead.
func (*GetSavingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_money_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSavingsResponse) GetTotalSavings() float64 {
	if x != nil {
		return x.TotalSavings
	}
	return 0
}

func (x *GetSavingsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_money_service_proto protoreflect.FileDescriptor

const file_proto_money_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/money_service.proto\x12\rmoney_service\",\n" +
	"\x11GetSavingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"U\n" +
	"\x12GetSavingsResponse\x12#\n" +
	"\rtotal_savings\x18\x01 \x01(\x01R\ftotalSavings\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency2a\n" +
	"\fMoneyService\x12Q\n" +
	"\n" +
	"GetSavings\x12 .money_service.GetSavingsRequest\x1a!.money_service.GetSavingsResponseB\rZ\v./pkg/protob\x06proto3"

var (
	file_proto_money_service_proto_rawDescOnce sync.Once
	file_proto_money_service_proto_rawDescData []byte
)

func file_proto_money_service_proto_rawDescGZIP() []byte {
	file_proto_money_service_proto_rawDescOnce.Do(func() {
		file_proto_money_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_money_service_proto_rawDesc), len(file_proto_money_service_proto_rawDesc)))
	})
	return file_proto_money_service_proto_rawDescData
}

var file_proto_money_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_money_service_proto_goTypes = []any{
	(*GetSavingsRequest)(nil),  // 0: money_service.GetSavingsRequest
	(*GetSavingsResponse)(nil), // 1: money_service.GetSavingsResponse
}
var file_proto_money_service_proto_depIdxs = []int32{
	0, // 0: money_service.MoneyService.GetSavings:input_type -> money_service.GetSavingsRequest
	1, // 1: money_service.MoneyService.GetSavings:output_type -> money_service.GetSavingsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_money_service_proto_init() }
func file_proto_money_service_proto_init() {
	if File_proto_money_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_money_service_proto_rawDesc), len(file_proto_money_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_money_service_proto_goTypes,
		DependencyIndexes: file_proto_money_service_proto_depIdxs,
		MessageInfos:      file_proto_money_service_proto_msgTypes,
	}.Build()
	File_proto_money_service_proto = out.File
	file_proto_money_service_proto_goTypes = nil
	file_proto_money_service_proto_depIdxs = nil
}
