services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: wb-money-clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP порт
      - "9000:9000"  # Native порт
    volumes:
      - ./clickhouse-db/data:/var/lib/clickhouse
      - ./clickhouse-db/logs:/var/log/clickhouse-server
      - ./clickhouse-db/config:/etc/clickhouse-server/config.d
      - ./clickhouse-db/users:/etc/clickhouse-server/users.d
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - clickhouse-network

networks:
  clickhouse-network:
    driver: bridge